---
title: "Capacity Demand and Supply Map"
author: "Kat Kyuchukova and Jocelyn Hu"
date: "4/9/2019"
output: html_document
---
```{r Packages}
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(tigris)
library(sf)
library(mosaic)
library(mapview)
library(leaflet)
library(leaflet.extras)
```

```{r Boston Neighborhood Shapefiles}
#boston neighborhood data!
boston_neighborhood <- read_sf("Boston_Neighborhoods/Boston_Neighborhoods.shp")
```


```{r API Key}
## define census API key and set it with census_api_key function

api_key <- "8fa9f8cc6afff6f16cfa41d92974f406a35636a6"
census_api_key(api_key)

## check API key

Sys.getenv("CENSUS_API_KEY")
```

```{r Getting the Variables}
#percentage of children under 6 with all parents in the labor force, 1 for single-parent household, 2 for two-parent household in each census tract in Boston.

#variables for all parents in the labor force (both double & single family households)
laborforcevars <- c("B23008_004", "B23008_010", "B23008_013")

laborforce_under6  <- get_acs(geography = "tract",
                     variables = laborforcevars,
                     survey="acs5",
                     state= "MA",
                     county="Suffolk",
                geometry=TRUE)

#get a sum of children with all parents in the labor force
laborforce_under6 <- laborforce_under6 %>%
  group_by(GEOID, NAME) %>%
  summarise(laborforcechildren = sum(estimate)) 

#get the total number of children under 6
under6total <- get_acs(geography = "tract",
                     variables = "B23008_002",
                     survey="acs5",
                     state= "MA",
                     county="Suffolk",
                geometry=TRUE)

#join the two files (by turning into data frame)
percentage_under_6 <- inner_join(laborforce_under6 %>% as.data.frame(), under6total %>% as.data.frame(), by = "GEOID")

#turning back into an sf object
percentage_under_6 <- percentage_under_6 %>%
  st_sf(sf_column_name = 'geometry.x')

#turn two numbers into a percentage
percentage_under_6 <- percentage_under_6 %>%
  mutate(percent_working = laborforcechildren/estimate*100)
```


```{r Supply Data Variables}
EECNEW5<-read.csv("masterdataframe_492019_tract.csv")

#early ed filter grouped by tract, summarized for capacity
EECNEW5_earlyed_tract <- EECNEW5 %>%
  filter(early_ed==TRUE) %>%
  group_by(GEOID, NAMELSAD) %>%
  summarise(sum_capacity = sum(Capacity))

#just a general early ed filter for later
EEC_earlyed <- EECNEW5 %>%
  filter(early_ed==TRUE, Weekdays_off_hours=="True")

EECNEW5_earlyed_tract$GEOID <- as.character(EECNEW5_earlyed_tract$GEOID)

EEC_geometry <- inner_join(EECNEW5_earlyed_tract %>% as.data.frame(), percentage_under_6 %>% as.data.frame(), by = "GEOID")

EEC_geometry <- EEC_geometry %>%
  select(GEOID, NAME.x,sum_capacity, geometry.x) %>%
  st_sf(sf_column_name = 'geometry.x')

View(EECNEW5_earlyed_tract)
```


```{r Child Care Deserts}
## took Kat's dataset and added variable indicating if there is at least 50 children under 6 with all parents in the workforce per tract

laborforce_under6_desert <- laborforce_under6 %>%
  mutate(atLeast50children = ifelse(laborforcechildren >= 50, "1", "0" ))

## joined the dataset above with the data set that wgave the ealry ed filter grouped by tract and summarized for early ed capacity

EEC_desert <- inner_join(EECNEW5_earlyed_tract %>% as.data.frame(), 
                         laborforce_under6_desert %>% as.data.frame(), by = "GEOID")

## created a ratio of estimated children under 6 with all parents in the workforce per tract over summarized early ed capacity per tract
## created a boolean variable to indicate if the ratio children:capacity is greater than 3:1, which would indicate a desert area in that tract

EEC_desert <- EEC_desert %>%
  mutate(ChildToCapacityRatio = laborforcechildren/sum_capacity) %>%
  mutate(EarlyEdChildCareDesert = ifelse(atLeast50children == "0", "FALSE",
                                ifelse(atLeast50children == "1" &
                                         ChildToCapacityRatio > 3.00, "TRUE", "FALSE"))) %>%
  select(GEOID, 
         NAMELSAD,
         NAME, 
         sum_capacity, 
         laborforcechildren,
         atLeast50children,
         ChildToCapacityRatio,
         EarlyEdChildCareDesert,
         geometry)

## the above code only gives us information for the tracts that provide early ed childcare 

## found it difficult to create a variable that shows if there is a tract that is completely missing an early ed child care provider (which is suppose to be registered as desert area)
## the attempt to create this variable is below

EECNEW5_desert <- EECNEW5 %>%
  group_by(GEOID) %>%
  mutate(EarlyEdProviderDesert = ifelse(early_ed == "TRUE", "FALSE", "TRUE")) %>%
  select(GEOID, NAME, NAMELSAD, early_ed, totalcapacity_early_ed, EarlyEdProviderDesert)

View(EEC_desert)
```

```{r}
glimpse(EEC_desert)
```

```{r Children Under 6 Percentage Map with Providers}
#making palettes
pal <- colorBin("YlOrRd", domain = percentage_under_6$percent_working)
percent6pal <- colorBin("YlOrRd", domain = percentage_under_6$percent_working)
infant_pal <- colorFactor(palette = c("white"),
                            levels = c("True"))

#transform sf type to work with leaflet
percentage_under_6 <- percentage_under_6 %>%
  st_transform(crs = "+init=epsg:4326")

#make map
leaflet(percentage_under_6) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(percent_working),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal, 
              values = ~percent_working,
              title = "Percentage of children",
              opacity = 1) %>%
  addCircleMarkers(data = EEC_earlyed,
                   ~lon,
                   ~lat,
                   radius = 3,
                   opacity = .8,
                   color = ~infant_pal(Weekdays_off_hours),
                   group = "Show providers with after school care for early ed",
                   label = ~as.character(Name))%>%
  addLayersControl(overlayGroups = c("Show providers with after school care for early ed"))

```



```{r Capacity for Children Under 6 Map}
#making palettes
pal2 <- colorBin("YlOrRd", domain = EEC_geometry$sum_capacity)

#transform sf type to work with leaflet
EEC_geometry <- EEC_geometry %>%
  st_transform(crs = "+init=epsg:4326")

#make map
leaflet(EEC_geometry) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal2(sum_capacity),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11) %>%
  addLegend("topleft", 
              pal = pal2, 
              values = ~sum_capacity,
              title = "Capacity",
              opacity = 1)
```

