---
title: "Capacity Demand Map FINAL"
author: "Kat Kyuchukova"
date: "4/13/2019"
output: html_document
---

#packages
```{r Packages}
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(tigris)
library(sf)
library(mosaic)
library(mapview)
library(leaflet)
library(leaflet.extras)
```

#data/APIs
```{r}
boston_neighborhood <- read_sf("Boston_Neighborhoods/Boston_Neighborhoods.shp")
tractneighborho <- read.csv("tractneighborho.csv")
api_key <- "8fa9f8cc6afff6f16cfa41d92974f406a35636a6"
census_api_key(api_key)
```

Adding geometry into tract neighborhood file
```{r}
#add back geometry
masterdataframe_tract_g <- cbind(classification2, EECMaster49)
masterdataframe_tract_neighborho_g <- cbind(classification4, masterdataframe_tract_g)

tractneighborho_geo<-masterdataframe_tract_neighborho_g%>%
  select(Name_neighborho,Neighborho_neighborho,geometry_neighborho,NAMELSAD_tract,GEOID_tract,geometry_tract)

tractneighborho_geo<-tractneighborho_geo[!duplicated(tractneighborho_geo[,'GEOID_tract']),]
```


Getting the variables
```{r}
#percentage of children under 6 with all parents in the labor force, 1 for single-parent household, 2 for two-parent household in each census tract in Boston.

#variables for all parents in the labor force (both double & single family households)
laborforcevars <- c("B23008_004", "B23008_010", "B23008_013")

laborforce_under6  <- get_acs(geography = "tract",
                     variables = laborforcevars,
                     survey="acs5",
                     state= "MA",
                     county="Suffolk",
                geometry=TRUE)

#get a sum of children with all parents in the labor force
laborforce_under6 <- laborforce_under6 %>%
  group_by(GEOID, NAME) %>%
  summarise(laborforcechildren = sum(estimate))

#get the total number of children under 6
under6total <- get_acs(geography = "tract",
                     variables = "B23008_002",
                     survey="acs5",
                     state= "MA",
                     county="Suffolk",
                geometry=TRUE)

#join the two files (by turning into data frame)
percentage_under_6 <- inner_join(laborforce_under6 %>% as.data.frame(), under6total %>% as.data.frame(), by = "GEOID")

#merge this with neighborhood tract information
colnames(tractneighborho_geo)[5] <- "GEOID"
percentageunder6_neighborhood <- inner_join(percentage_under_6, tractneighborho_geo, by ="GEOID")

#turning back into an sf object
percentageunder6_neighborhood <- percentageunder6_neighborhood %>%
  select(GEOID, Name_neighborho, NAMELSAD_tract, laborforcechildren, estimate, geometry_neighborho, geometry_tract) %>% 
  st_sf(sf_column_name = 'geometry_neighborho')

percentageunder6_tract <- percentageunder6_neighborhood %>%
  select(GEOID, Name_neighborho, NAMELSAD_tract, laborforcechildren, estimate, geometry_neighborho, geometry_tract) %>% 
  st_sf(sf_column_name = 'geometry_tract')

#getting estimates per neighborhood and tract with neighborhood geometry and tract geometry
neighborho_demand <- percentageunder6_neighborhood %>%
  group_by(Name_neighborho) %>%
  summarise(laborforce = sum(laborforcechildren))

neighborho_demand_tract <- percentageunder6_tract %>%
  group_by(NAMELSAD_tract) %>%
  summarise(laborforce = sum(laborforcechildren))


```


supply data
```{r}
EECNEW5<-read.csv("masterdataframe_tract.csv")

#early ed filter grouped by tract, summarized for capacity
EECNEW5_earlyed_tract <- EECNEW5 %>%
  filter(early_ed=="True") %>%
  group_by(GEOID_tract, NAMELSAD_tract) %>%
  summarise(sum_capacity = sum(Capacity))


EECNEW5_earlyed_tract$GEOID <- as.character(EECNEW5_earlyed_tract$GEOID_tract)

EEC_geometry <- inner_join(EECNEW5_earlyed_tract %>% as.data.frame(), percentage_under_6 %>% as.data.frame(), by = "GEOID")

EEC_geometry <- EEC_geometry %>%
  st_sf(sf_column_name = 'geometry.x')

#merge neighborhood information
EECcapacity <- inner_join(EEC_geometry %>% as.data.frame(), tractneighborho_geo, by ="GEOID")

EEC_neigh_geometry <- EECcapacity %>%
  st_sf(sf_column_name = 'geometry_neighborho')

EEC_tract_geometry <- EECcapacity %>%
  st_sf(sf_column_name = 'geometry_tract')

#summarizing capacity!!
neighborho_capacity <- EEC_neigh_geometry %>%
  group_by(Name_neighborho) %>%
  summarise(slots = sum(sum_capacity))

neighborho_capacity_tract <- EEC_tract_geometry %>%
  group_by(NAMELSAD_tract.x) %>%
  summarise(slots = sum(sum_capacity))
```

Getting difference between slot capacity and demand by neighborhood
```{r}
#more merging baby!!!
EEC_census <- inner_join(neighborho_capacity %>% as.data.frame(), neighborho_demand %>% as.data.frame(), by = "Name_neighborho")

EEC_census <- EEC_census %>%
  select(Name_neighborho, slots, laborforce, geometry_neighborho.x) %>%
  st_sf(sf_column_name = 'geometry_neighborho.x') %>%
  mutate(differenceslots = slots-laborforce,
         ratioslots= slots/laborforce,
         more_slots = ifelse(differenceslots>0, "yes", "no"))
```



Make the map: two by tract (supply and demand), one by neighborhood for difference 
```{r}
#making palettes
pal <- colorBin("YlOrRd", domain = neighborho_demand_tract$laborforce)
percent6pal <- colorBin("YlOrRd", domain = percentage_under_6$percent_working)
infant_pal <- colorFactor(palette = c("white"),
                            levels = c("TRUE"))

#transform sf type to work with leaflet
neighborho_demand <- neighborho_demand %>%
  st_transform(crs = "+init=epsg:4326")

neighborho_demand_tract <- neighborho_demand_tract %>%
  st_transform(crs = "+init=epsg:4326")

neighborho_capacity <- neighborho_capacity %>%
  st_transform(crs = "+init=epsg:4326")

neighborho_capacity_tract <- neighborho_capacity_tract %>%
  st_transform(crs = "+init=epsg:4326")

##DEMAND BY TRACT
pal <- colorBin("YlOrRd", domain = neighborho_demand_tract$laborforce)
leaflet(neighborho_demand_tract) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(laborforce),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal, 
              values = ~laborforce,
              opacity = 1)

##CAPACITY BY TRACT
pal <- colorBin("YlOrRd", domain = neighborho_capacity_tract$slots)
leaflet(neighborho_capacity_tract) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(slots),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal, 
              values = ~slots,
              opacity = 1)

#DIFFERENCE BY NEIGHBORHOOD
pal <- colorFactor("YlOrRd", domain = EEC_census$more_slots)
leaflet(EEC_census) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(more_slots),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal, 
              values = ~more_slots,
              opacity = 1)

pal <- colorBin("YlOrRd", domain = EEC_census$ratioslots)
leaflet(EEC_census) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(ratioslots),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal, 
              values = ~ratioslots,
              opacity = 1)

```



```{r}
#making palettes
pal2 <- colorBin("YlOrRd", domain = EEC_geometry$sum_capacity)

#transform sf type to work with leaflet
EEC_geometry <- EEC_geometry %>%
  st_transform(crs = "+init=epsg:4326")

#make map
leaflet(EEC_geometry) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal2(sum_capacity),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11) %>%
  addLegend("topleft", 
              pal = pal2, 
              values = ~sum_capacity,
              title = "Capacity",
              opacity = 1)
```



