---
title: "Ethics Statement: Community Labor United Capstone Project"
author: "Kat Kyuchukova, Jocelyn Hu, Paige Patrick"
date: "4/25/2019"
output: html_document
---

The ethical concerns surrounding this project are more about the moral obligations to support Community Labor United (CLU), and the working-class families they advocate for in the Great Boston Area. We believe there is a social responsibility in promoting research that benefits marginalized groups of individuals. We are fortunate enough to be working with data that is publicly available on government owned websites, so the data used in this research is as transparent as possible. The public data available is messy and incomplete, which required immense cleaning. When wrangling the data, we consciously overestimate in favor of the current childcare system framework, provided by the Department of Early Education and Care (EEC), though our clients are pushing for reform in this structure. This means that even though the data we are dealing with is only available in estimates, the gap we are showing is one that is guaranteed to exist, because we give the childcare providers the benefit of the doubt at all steps of the process.This ensures that the conclusions drawn from our visualizations are not exaggerated in favor of our clients motives. Thus, we are confident that the claims we make about the inadequacy of the EEC are as accurate as possible.


As far as the long term implications of this work, these findings are to be presented to convince the public as well as potential donors of a need for a network of childcare providers for unstandardized care. Therefore, the goal of this work is to lead to policy changes. There are of course ethical implications in the results we present, because the resulting policy change will be affecting the lives of workers across Boston who need childcare at nonstandard hours, and many of these workers belong to marginalized identities (women, people of color, low-income people). However, we believe that our work has accurately represented the vast gap in the need for childcare at nonstandard hours and the childcare that the EEC provides. The resulting policy changes will be ones that hopefully benefit everybody involved, but especially the workers so desperately in need of childcare. We have taken caution to prioritize ethics at every step of this process, and we believe our resulting project is one that works to do the most good for society. 
