---
title: "Untitled"
author: "Jocelyn Hu"
date: "April 27, 2019"
output: html_document
---


##RUN PROVIDERS_IN_POLYGONS.RMD before this!!!!
```{r Packages}
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(tigris)
library(sf)
library(mosaic)
library(mapview)
library(leaflet)
library(leaflet.extras)
```

```{r}
#Read in boston neighborhood data
boston_neighborhood <- read_sf("Boston_Neighborhoods/Boston_Neighborhoods.shp")
```




```{r API Key}
## define census API key and set it with census_api_key function

api_key <- "8fa9f8cc6afff6f16cfa41d92974f406a35636a6"
census_api_key(api_key)

## check API key

Sys.getenv("CENSUS_API_KEY")
```

```{r}
med_income <- get_acs(geography = "tract",
                    variables = "B19013_001",
                    survey="acs5",
                    state= "MA",
                    county="Suffolk",
               geometry=TRUE)
```


Adding geometry into tract neighborhood file
```{r}
#add back geometry
masterdataframe_tract_g <- cbind(classification2, EECMaster49)
masterdataframe_tract_neighborho_g <- cbind(classification4, masterdataframe_tract_g)

tractneighborho_geo<-masterdataframe_tract_neighborho_g%>%
  select(Name_neighborho,Neighborho_neighborho,geometry_neighborho,NAMELSAD_tract,GEOID_tract,geometry_tract)

tractneighborho_geo<-tractneighborho_geo[!duplicated(tractneighborho_geo[,'GEOID_tract']),]
```


```{r}
#merge this with neighborhood tract information
colnames(tractneighborho_geo)[5] <- "GEOID"
income_neighborhood <- inner_join(med_income, tractneighborho_geo, by ="GEOID")

#turning back into an sf object
income_neighborhood <- income_neighborhood %>%
  select(GEOID, Name_neighborho, NAMELSAD_tract, moe, estimate, geometry_neighborho, geometry_tract) %>% 
  st_sf(sf_column_name = 'geometry_neighborho')

income_tract <- income_neighborhood %>%
  select(GEOID, Name_neighborho, NAMELSAD_tract, moe, estimate, geometry_neighborho, geometry_tract) %>% 
  st_sf(sf_column_name = 'geometry_tract')
```

```{r}
#getting estimates per neighborhood and tract with neighborhood geometry and tract geometry
neighborho_demand <- income_neighborhood %>%
  group_by(Name_neighborho) %>%
  summarise(medincome = mean(estimate))

neighborho_demand_tract <- income_tract %>%
  group_by(NAMELSAD_tract) %>%
  summarise(medincome = mean(estimate))


neighborho_demand%>%
  select(Name_neighborho,medincome)
```

```{r}

colnames(neighborho_demand)<-c("Name_neighborho","var","geo")


colnames(EEC_census_bar)<-c("order","Name_neighborho","var")


neighborho_demand$geo<-NULL
```

```{r}

tablesupply<-EEC_census_bar%>%
  select(Name_neighborho,var)%>%
  na.omit()%>%
  mutate(name = "childcare_ratio")%>%
  mutate(var=var*50000)%>%
  arrange(desc(var))%>%
  group_by(Name_neighborho)%>%
  mutate(order = 21:1)

tabledemand<-neighborho_demand%>%
  as.data.frame()%>%
  na.pass()%>%
  mutate(name = "income")%>%
  group_by(Name_neighborho)%>%
  mutate(order = 0)

library(plyr)
plottable<-as.data.frame(rbind(tablesupply,tabledemand))
```

```{r}
library(ggplot2)
library(RColorBrewer)
cbPalette <- c( "#52854C", "#D16103")
ggplot(plottable,aes(x=reorder(Name_neighborho,order), y = var, fill = name))+scale_y_continuous("Median Income($)",sec.axis = sec_axis(~./50000, name = "Ratio"))+coord_flip()+
  geom_bar(stat="identity",position="dodge") + ggtitle( "Childcare ratio vs. Mean Anuual Income by neighborhood")+ xlab("Neighborhoods")+  ylab("Median Income($)") + geom_hline(yintercept=1)+theme(panel.background = element_rect(fill='white', colour='white'))+scale_fill_manual(values=cbPalette)
```

```{r}
library(ggplot2)
ggplot(EEC_census_bar,aes(x =reorder(Name_neighborho,ratioslots), y = ratioslots)) +
  geom_bar(fill="orange", stat="identity") + ggtitle( "Childcare ratio by neighborhood")+ xlab("Neighborhoods")+  ylab("Ratio of children under 6 from working families to available slots for early ed") + geom_hline(yintercept=1)+coord_flip()+theme(panel.background = element_rect(fill='white', colour='white'))
```
