---
title: "Shiny"
author: "Paige Patrick"
date: "4/2/2019"
output: html_document
---

```{r Packages}
library(shiny)
library(shinydashboard)
library(leaflet) 

## OTHER .RMD FILES YOU NEED TO RUN BEFORE HAND
## "Capacity Demand Map.Rmd"
```

```{r Empty Dashboards}

header <- dashboardHeader()
sidebar <- dashboardSidebar()
body <- dashboardBody()

ui <- dashboardPage(header, sidebar, body)

server <- function(input, output)  {}

#shinyApp(ui, server)

```

```{r Header}

## HEADER

header <- dashboardHeader(
  title = "CLU",
  dropdownMenu(type = "messages",
               messageItem(
                 from = "Paige",
                 message = "Cats are awesome",
                 href = "https://www.purrfectpost.com/top-10-reasons-cats-are-awesome/"
                 )),
  dropdownMenu(type = "notifications",
               notificationItem(
                 text = "Why do I love cats so much?",
                 href = "https://www.psychologytoday.com/us/blog/intimacy-path-toward-spirituality/201507/if-you-love-cats-may-be-why"
                 )),
  dropdownMenu(type = "tasks",
               taskItem(
                 text = "Look at cat videos right meow!",
                 value = 50
                 ))
)

```

```{r Sidebar and Body}

## SIDEBAR

sidebar <- dashboardSidebar(
  sidebarMenu(
    
    ## INRODUCTION
    
    menuItem("Introduction",
             tabName = "introduction"),
    
    ## CAPACITY
    
    menuItem("Capacity",
             tabName = "capacity"
             ),
    
    ## HOURS
    
    menuItem("Hours",
             tabName = "hours"
             ),
    
    ##SUBSIDY
    
    menuItem("Subsidy",
             tabName = "subsidy"),
    
    ##MEHODOLOGY
    
    menuItem("Methodology",
             tabName = "methodology")
  )
)

## BODY

body <- dashboardBody(
  tabItems(
    
    ## INTRODUCTION
    
    tabItem(tabName = "introduction",
            title = "Introduction",
            tags$br(),
            tags$b("Hey there friend! "),
            ## Any text immediately following will NOT be on a seperate line
            ## tags$b/em() = text is bold/italicized 
            tags$em("Here's a brief overview of hours, capacity, and subsidy"),
            ## tags$br() = line break
            tags$br()
            ),
    
    ## CAPACITY
    
    # tabItem(tabName = "capacity",
    #         tags$h1("Number of children under 6 with all parents in the labor
    #                 force, per tract"),
    #         tags$br(),
    #         leafletOutput("laborforce_demand"),
    #         tags$br(),
    #         tags$h1("Number of slots for Early Education Providers, per tract"),
    #         leafletOutput("slots_supply"),
    #         tags$h1("Ratio of Number of Children to Avaliable Number of Slots, per neighborhood"),
    #         leafletOutput("ratioslots_gap"),
    #         tags$br(),
    #         tags$br(),
    #         plotOutput("all_neighborhoods_bar"),
    #         tags$br(),
    #         tags$br(),
    #         plotOutput("top_5_neighborhoods_bar")
    #         ),
    
    tabItem(tabName = "capacity",
            tags$h1("General Title for Capacity"),
            tags$h1("Percent of children under 6 with all parents in the labor
                    force"),
            tags$br(),
            leafletOutput("capacity_demand_map"),
            tags$br(),
            fluidRow(
              box(
                width = 6,
                title = "Children Under 6 with All Parents in the Labor Force",
                em("(per tract)"),
                br(),
                leafletOutput("laborforce_demand"),
                status = "danger"
                ),
              box(
                width = 6,
                title = "Slots for Early Eduction Providers",
                em("(per tract)"),
                br(),
                leafletOutput("slots_supply"),
                status = "danger"
                )
              ),
            tags$h1("Ratio of Number of Children to Available Number of Slot"),
            fluidRow(
              box(
                width = 8,
                title = "(per tract)",
                leafletOutput("ratioslots_gap"),
                status = "danger"),
              box(
                width = 4,
                title = "_______",
                em("blah blah blah"),
                status = "danger"
              )
              )
    ),
            tags$h1("Capacity for Early Education Providers"),
            leafletOutput("capacity_supply_map")
            ),
    ## HOURS
    
    tabItem(tabName = "hours",
            tags$h1("Percent of People Who Work Irregular Hours (per tract)"),
            tags$br(),
            tags$br(),
            fluidRow(
              box(
                width = 4,
                title = "Early Morning Hours",
                em("leaving home between 12:00am - 6:59am"),
                em(" "),
                br(),
                leafletOutput("percent_early"),
                status = "danger"
                ),
              box(
                width = 4,
                title = "Early Evening Hours",
                em("leaving home between 11:00am - 3:59pm"),
                em(" "),
                br(),
                leafletOutput("percent_evening"),
                status = "danger"
                ),
              box(
                width = 4,
                title = "Late Evening & Overnight Hours",
                em("leaving home between 4:00pm - 11:59pm"),
                em(" "),
                br(),
                leafletOutput("percent_overnight"),
                status = "danger"
              )
            ),
            tags$h1("General Irregular Hours Demand"),
            "Look at my cool dashboard",
            tags$head(
              tags$style(
                        HTML('
                            h3 {
                                font-weight: bold;
                            }
                            ')
                        )
              ),
            fluidRow(
              box(
                width = 12,
                title = "Regular Box, Row 1",
                "Cats, nothing but cats",
                status = "danger"
                )
              ),
            fluidRow(
              column(width = 6,
                     infoBox(
                       width = NULL,
                       title = "Regular Box, Row 2, Column 1",
                       subtitle = "Gimme those cats",
                       icon = icon("star")
                       )
                     ),
              column(width = 6,
                     infoBox(
                       width = NULL,
                       title = "Regular Box, Row 2, Column 2",
                       subtitle = "Don't let them end",
                       color = "green",
                       icon = icon(name = "refresh",
                                   class = "fa-1x fa-spin")
                       )
                     )
              )
            ),
    
    ## SUBSIDY
    
    tabItem(tabName = "subsidy",
            tabBox(
              title = "Subsidy Key Concepts",
              tabPanel("Subsidy concept 1", "What we want to say about concept 1"),
              tabPanel("Subsidy concept 2", "What we want to say about concept 2")
              )
            ),
    
    ## METHODOLOGY
    
    tabItem(tabName = "methodology",
            fluidRow(
              column(width = 12,
                     box(
                       title = "Capacity",
                       width = NULL,
                       solidHeader = TRUE, 
                       collapsible = TRUE,
                       collapsed = FALSE,
                       status = "info",
                       tags$h4("Percent of Children Under 6 with all parents in
                               the labor force"),
                       em("This demand variable was created using information provided by 
                         the 2016 American Community Survice data, which we accessed through tidycensus in R."),
                       br(),
                       br(),
                       p("Wtihin the ACS data, there were three distinct variables that recorded number of parents
                         in the labor force with children under 6 for each census tract in the Boston area. 
                         One of the variables (B23008_004) gave us the parents in the labor force that came from a 
                         2-parent household, while the other two variables (B23008_010, B23008_013) gave us the parents
                         in the labor force that came from a 1-parent household. Using this information, we were to get
                         the total sum of all children with all parents in the labor force. Using the ACS data, we then 
                         extracted the total number of children under 6 per tract (B23008_002).",
                         style = "font-family: 'times'; font-si16pt"),
                       strong("We were able to find the percent of children under 6 with all parents in the labor 
                              force per tract, by taking the sum of children with all parents in the labor force over 
                              the estimated _______.",
                         style = "font-family: 'times'; font-si16pt"),
                       br(),
                       tags$h4("Capacity for Early Education Providers"),
                       em("This supply variable was created using the EEC dataset given to us by Community Labor United."),
                       br(),
                       br()
                     ),
                     box(
                       title = "Hours",
                       width = NULL,
                       solidHeader = TRUE,
                       collapsible = TRUE,
                       collapsed = TRUE,
                       status = "info",
                       p("p creates a paragraph of text."),
                       p("A new p() command starts a new paragraph. Supply a style
                        attribute to change the format of the entire paragraph.",
                        style = "font-family: 'times'; font-si16pt"),
                       strong("strong() makes bold text."),
                       em("em() creates italicized (i.e, emphasized) text."),
                       br(),
                       code("code displays your text similar to computer code"),
                       div("div creates segments of text with a similar style. This
                           division of text is all blue because I passed the argument
                           'style = color:blue' to div", style = "color:blue"),
                       br(),
                       p("span does the same thing as div, but it works with",
                         span("groups of words", 
                              style = "color:blue"),
                         "that appear inside a paragraph.")
                     ),
                     box(
                       title = "Subsidy",
                       width = NULL,
                       solidHeader = TRUE,
                       collapsible = TRUE,
                       collapsed = TRUE,
                       status = "info",
                        "Box Content"
                     )
                     )
            ))
  )


```


```{r UI and Server}

## UI 

ui <- dashboardPage(skin = "purple",
                    header = header,
                    sidebar = sidebar,
                    body = body,
                    header = header_test,
                    sidebar = sidebar1,
                    body = body1
                    )
## SERVER

server <- function(input, output) {
  ## CAPACITY
  output$laborforce_demand <- renderLeaflet({
    leaflet(neighborho_demand_tract) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_laborforce(laborforce),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  output$capacity_demand_map <- renderLeaflet({
    leaflet(percentage_under_6) %>%
  addProviderTiles("CartoDB")  %>%
  addPolygons(fillColor = ~pal(percent_working),
  weight = 2,
  opacity = .8,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7) %>%
  addPolygons(data=boston_neighborhood, weight = 2, opacity = 1, fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11.5) %>%
  addLegend("topleft", 
              pal = pal_laborforce, 
              values = ~laborforce,
              opacity = 1,
              title="Number")
  })
  
  output$slots_supply <- renderLeaflet({
    leaflet(neighborho_capacity_tract %>%
              pal = pal, 
              values = ~percent_working,
              title = "Percentage of children",
              opacity = 1) %>%
  addCircleMarkers(data = EEC_earlyed,
                   ~lon,
                   ~lat,
                   radius = 3,
                   opacity = .8,
                   color = ~infant_pal(Weekdays_off_hours),
                   group = "Show providers with after school care for early ed",
                   label = ~as.character(Name))%>%
  addLayersControl(overlayGroups = c("Show providers with after school care for early ed"))
    })
  output$capacity_supply_map <- renderLeaflet({
    leaflet(ECC_geometry) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal2(sum_capacity),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      addPolygons(data=boston_neighborhood, weight = 2, opacity = 1,
                  fillOpacity=0, stroke=TRUE, color="black", label=~Name) %>%
      #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_slots, 
                values = ~slots,
                opacity = 1,
                title = "Number")
  })
  
  output$ratioslots_gap <- renderLeaflet({
    leaflet(EEC_census) %>%
      addProviderTiles("CartoDB")  %>% 
      addPolygons(fillColor = ~pal_ratioslots(ratioslots),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_ratioslots, 
                values = ~ratioslots,
                opacity = 1,
                title = "Children:Slots")
  })
  
  output$all_neighborhoods_bar <- renderPlot({
    ggplot(EEC_census_bar, 
           aes(x = reorder(Name_neighborho,-ratioslots), y = ratioslots, fill =Name_neighborho)) + 
      geom_bar(colour = "black", 
           stat = "identity") + 
      ggtitle( "Neighborhood ranking by desert ratio") + 
      xlab("Neighborhoods") + 
      ylab("Desert Ratio (Population under 6/Capacity for early ed")
  })
  
  output$top_5_neighborhoods_bar <- renderPlot({
    ggplot(EEC_census_bar5,
           aes(x = reorder(Name_neighborho,-ratioslots), y = ratioslots, fill = Name_neighborho)) +
      geom_bar(colour = "black", stat = "identity") + 
      ggtitle( "Top 5 Neighborhood ranking with the highest desert ratio") + 
      xlab("Neighborhoods") + 
      ylab("Desert Ratio (Population under 6/Capacity for early ed")
  })
  ## HOURS
  output$percent_early <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_early(percent_early),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_early, 
                values = ~percent_early,
                opacity = 1,
                title = "Percentage")
  })
  
  output$percent_evening <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_evening(percent_evening),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_evening, 
                values = ~percent_evening,
                opacity = 1,
                title="Percentage")
  })
  
  output$percent_overnight <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_overnight(percent_overnight),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_overnight, 
                values = ~percent_overnight,
                opacity = 1,
                title="Percentage")
  })
  
  output$weekdays_offhours <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal(aggregate_percent),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addCircleMarkers(data = EEC_earlyed,
                       ~lon,
                       ~lat,
                       radius = 2.5,
                       opacity = 1,
                       color = ~infant_pal(Weekdays_off_hours),
                       label = ~as.character(Capacity),
                       labelOptions = labelOptions(noHide = TRUE),
                       group= "Show childcare providers with off hours weekday care") %>%
      addLayersControl(overlayGroups = c("Show childcare providers with off hours weekday care")) %>%
      addLegend("topleft", 
                pal = pal, 
                values = ~aggregate_percent,
                opacity = 1,
                title="Aggregated Percentage")
  })
                pal = pal2, 
                values = ~sum_capacity,
                title = "Capacity",
                opacity = 1)
  }) 
}

# server <- function(input, output, session) {
#   reactive_data <- reactiveFileReader(
#     intervalMillis = 1000,
#     session = session,
#     filePath = "file.csv",
#     #readFunc = read.csv
#     readFunc = function
#     (filePath) {
#       read.csv(url(filePath))
#     }
#   )
# }
#   output$printed_data <- renderPrint({
#     reactive_data()
#   })
# }

## SHINYAPP

shinyApp(ui, server)

```


