---
title: "Real Shiny"
author: "Paige Patrick"
date: "4/25/2019"
output: html_document
---

```{r Packages}
library(shiny)
library(shinydashboard)
library(leaflet) 
library(ggplot2)

## FILES YOU NEED TO RUN BEFORE HAND:
## providers_in_polygons.Rmd
## Capacity Map FINAL.Rmd
## Hours_Supply_Maps_by_tract.Rmd
## Hours Demand Maps FINAL.Rmd
```

```{r Empty Dashboards}

header <- dashboardHeader()
sidebar <- dashboardSidebar()
body <- dashboardBody()

ui <- dashboardPage(header, sidebar, body)

server <- function(input, output)  {}

#shinyApp(ui, server)

```

```{r Header}

## HEADER

header <- dashboardHeader(
  title = "CLU: Childcare",
  dropdownMenu(type = "messages",
               messageItem(
                 from = "Community Labor United",
                 message = "Contact us for more information",
                 href = "http://massclu.org/about/"
                 )),
  dropdownMenu(type = "notifications",
               notificationItem(
                 text = "CLU: Care That Works",
                 href = "http://massclu.org/initiatives/#childcare"
                 ),
               notificationItem(
                 text = "Childcare Aware",
                 href = "https://www.childcareaware.org/"
               ))
)

```

```{r Sidebar and Body}

## SIDEBAR

sidebar <- dashboardSidebar(
  sidebarMenu(
    
    ## INRODUCTION
    
    menuItem("Introduction",
             tabName = "introduction"),
    
    ## CAPACITY
    
    menuItem("Capacity",
             tabName = "capacity"
             ),
    
    ## HOURS
    
    menuItem("Hours",
             tabName = "hours"
             ),
    
    ##MEHODOLOGY
    
    menuItem("Methodology",
             tabName = "methodology")
  )
)

## BODY

body <- dashboardBody(
  tabItems(
    
    ## INTRODUCTION
    
    tabItem(tabName = "introduction",
            title = "Introduction",
            tags$h1("Community Labor United - Childcare"),
            tags$br(),
            tags$em("Community Labor United is a non-profit organization that is currently working to investigate the negligence in childcare provision for low and middle-income families within the Greater Boston Area, in order to promote reforms within the current system provided by the Department of Early Education and Care. "),
            tags$br(),
            tags$br(),
            tags$br(),
            tags$strong("Overview:"),
            tags$br(),
            tags$br(),
            p("Using interactive maps, the research outlined in this paper highlights two gaps in the current childcare structure:"),
            tags$div(tags$ul(
              tags$li("The first being how the hours that early education childcare providers keep do not support families that work primarily nonstandard schedules."),
              tags$li("The second being how the number of slots for early education provision does not align with the number of children age five and under that live within each neighborhood and census tract."),
              style = "font-size: 15px"),
            p("The interaction between these two gaps drastically impacts the livelihood of working class families and it is our hope that this research will provide evidence that the current system in place needs to be reconstructed, in order to support all households in Massachusetts."),
            p("This research emphasizes early education childcare demands needed for low and middle-income families working nonstandard hours in the Great Boston Area. More specifically, this research focuses on illustrating a disparity in operating hours and capacity for childcare providers on the neighborhood level and census tract level.")
    )
    ),
    
    ## CAPACITY

    tabItem(tabName = "capacity",
            tags$h1("Early Ed Childcare Slots to Childcare Needs Comparison"),
            tags$br(),
            tags$br(),
            fluidRow(
              box(
                width = 6,
                title = "Children Under 6 Who Need Childcare",
                em("(per tract)"),
                br(),
                leafletOutput("laborforce_demand"),
                status = "danger"
                ),
              box(
                width = 6,
                title = "Childcare Slots for Early Education Providers",
                em("(per tract)"),
                br(),
                leafletOutput("slots_supply"),
                status = "danger"
                )
              ),
            tags$h1("Ratio of Number of Children to Available Number of Slots"),
            tags$em("(per neighborhood)"),
            fluidRow(
              box(
                width = 7,
                leafletOutput("ratioslots_gap"),
                status = "danger"),
              box(
                width = 5,
                plotOutput("ratioslots_bar"),
                status = "danger"
              )
              )
    ),
    
    ## HOURS

    tabItem(tabName = "hours",
            tags$h1("Percent of People Who Work Nonstandard Hours (per tract)"),
            tags$br(),
            tags$br(),
            fluidRow(
              box(
                width = 4,
                title = "Workers with Early Morning Shifts",
                em("leaving home between 12:00am - 6:59am"),
                em(" "),
                br(),
                leafletOutput("percent_early"),
                status = "danger"
                ),
              box(
                width = 4,
                title = "Workers with Early Evening Shifts",
                em("leaving home between 11:00am - 3:59pm"),
                em(" "),
                br(),
                leafletOutput("percent_evening"),
                status = "danger"
                ),
              box(
                width = 4,
                title = "Workers with Late Evening & Overnight Shifts",
                em("leaving home between 4:00pm - 11:59pm"),
                em(" "),
                br(),
                leafletOutput("percent_overnight"),
                status = "danger"
              )
            ),
            tags$h1("Nonstandard Hours Demand"),
            fluidRow(
              box(
                width = 8,
                leafletOutput("aggregate_percent"),
                status = "danger"),
              box(
                width = 4,
                em("The aggregated percentage is the sum of the percentage of people with all nonstandard hours (Monday - Friday, 7:30am - 6:00pm)."),
                p("------"),
                em(" Each dot is a childcare provider. You can hover over each childcare provider to see the number of slots they have available for off-hour weekday care."),
                status = "danger"
              )
              )
    ),
    
    ## METHODOLOGY
    
    tabItem(tabName = "methodology",
            fluidRow(
              column(width = 12,
                     box(
                       title = "Capacity",
                       width = NULL,
                       solidHeader = TRUE, 
                       collapsible = TRUE,
                       collapsed = FALSE,
                       status = "info",
                       tags$br(),
                       tags$strong("Percent of Children Under 6 with All Parents in the Labor Force"),
                       tags$br(),
                       tags$br(),
                       tags$em("This demand variable was created using information provided by the 2016 American Community Survey data, which we accessed through tidycensus in R. All ACS data was filtered for Suffolk County, MA"),
                       tags$br(),
                       tags$br(),
                       tags$div(tags$ul(
                         tags$li("Within the ACS data, there were three distinct variables that recorded number of parents in the labor force with children under 6 for each census tract in the Boston area."),
                         tags$li("ACS variable B23008_004 (number of children under 6 from a 2-parent household with both parents in the labor force),  ACS variables B23008_010 (single working father household), B23008_013 (single working mother household). We then added these values to obtain the count of all children under 6 with all parents in the labor force. "),
                         tags$li("We then extracted the total number of children under 6 per tract (ACS variable B23008_002). We divided the previous sum by this total number of children under 6 to obtain the percent of children under 6 with parents in the labor force."),
                         style = "font-size: 15px"),
                         tags$br(),
                         tags$strong("Capacity for Early Education Provider"),
                         tags$br(),
                         tags$br(),
                         tags$em("This supply variable was created using the EEC dataset given to us by Community Labor United. The dataset was filtered for providers that provide care for children 6 and under (early education care), as this was our focus."),
                         tags$br(),
                         tags$br(),
                         p("To get a sense of the slots available for early education provision, we take the EEC dataset and use Python software to filter only for providers that provide early education childcare based three variables: rates, age, and licensed capacity."),
                         tags$br(),
                         tags$div(tags$ul(
                         tags$li("First, we obtain information on service availability from the Rates variable that list the prices of childcare service for four age groups, including infants, toddlers, preschoolers, and school age. The spread the Rates variable into 4 categorical variables of all age groups to use them as filters later on. After that, we use if statements and dictionary reader in Python to take out providers from the original datasets that only offer price information of cares for school-aged children and therefore only care for school-aged children. "),
                         tags$li("Second, for providers with no Rates data, we use Min Age and Max Age variables to take out providers with “6” as the minimum age. This procedure is based on two assumptions. We assume that providers that have no Rates or Age data and that care for all age groups, including school-age, to be providers for early ed. Accordingly, we consciously overestimated in favor of the current childcare system framework."),
                         style = "font-size: 15px")),
                         tags$br(),
                         tags$br(),
                         tags$strong("Capacity on the Tract and Neighboorhood Levels:"),
                         tags$br(),
                         tags$br(),
                         tags$div(tags$ul(
                           tags$li("First, we geocode the addresses of providers to map out all the providers. We then use the over function in R from rgeo and rgdal packages to figure out which tract or neighborhood on the polygon map each provider is located within. "),
                           tags$li("After that, we use the tidyverse package to group the providers by census tract, and calculated the total number of slots for early education childcare in each tract. We repeat this process for neighborhood so that we also have the total number of slots for early education childcare in each neighborhood. "),
                           tags$li("Finally, we merge these datasets with the respective geometry for each geography, to allow us to map the results."),
                           style = "font-size: 15px")),
                         tags$br(),
                         tags$br(),
                         tags$strong("Ratio of Children to Slots Available"),
                         tags$br(),
                         tags$br(),
                         tags$div(tags$ul(
                           tags$li("Divide the number of children in working families by the number of slots available. These calculations were done by tract and neighborhood. We use data provided by the shapefiles of neighborhoods and tracts figure out which neighborhood each tract is located within.
"),
                           style = "font-size: 15px"))
                     )),
                     box(
                       title = "Hours",
                       width = NULL,
                       solidHeader = TRUE,
                       collapsible = TRUE,
                       collapsed = TRUE,
                       status = "info",
                       tags$br(),
                       tags$strong("Quantification of Nonstandard Work Shifts"),
                       tags$br(),
                       tags$br(),
                       tags$em("This demand variable was created using information provided by the 2016 American Community Survey data, which we accessed through tidycensus in R. All ACS data was filtered for Suffolk County, MA."),
                       tags$br(),
                       tags$br(),
                       tags$p("Based on previous methodology, we split nonstandard hours into three categories:"),
                       tags$div(tags$ul(
                         tags$li("Early morning: leaving for work anytime between 12am-6:29am (corresponds to ACS variables B08302_002, B08302_003, B08302_004, and B08302_005)"),
                         tags$li("Evenings: leaving for work anytime between 11am-3:59pm (corresponds to ACS variables B08302_013 and B08302_014)"),
                         tags$li("Late evenings/overnight: leaving for work anytime between 4pm-11:59pm (corresponds to ACS variable B08302_015)"),
                         style = "font-size: 15px"),
                         tags$p("We divided each of these values by the total number of workers in Suffolk County, to obtain percentage estimates for each nonstandard shift category."),
                         tags$br(),
                         tags$br(),
                         tags$strong("Aggregated Nonstandard Shift Map"),
                         tags$br(),
                         tags$br(),
                         tags$div(tags$ul(
                         tags$li("To create the aggregate map, we added the three nonstandard shift counts to obtain one general nonstandard shift count, and divided this by the total number of workers to obtain an aggregate percentage."),
                         tags$li("We then filtered the EEC dataset to show only providers that provide care outside of nonstandard working hours, 7:30am-6pm, based on 14 variables that show the open and close time on each day of the week (note: the dataset is already filtered for early education providers only). We then showed these providers with the option to see how many off-hour slots are available at that provider."),
                         style = "font-size: 15px"))
                     )
                     )
            ))
  )
))

```


```{r UI and Server}

## UI 

ui <- dashboardPage(skin = "purple",
                    header = header,
                    sidebar = sidebar,
                    body = body
                    )
## SERVER

server <- function(input, output) {
  ## CAPACITY
  output$laborforce_demand <- renderLeaflet({
    leaflet(neighborho_demand_tract) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_laborforce(laborforce),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, stroke=TRUE, color="black", label=~Name) %>% #adding neighborhood data
  setView(lng = -71.057083, 
          lat = 42.361145, 
          zoom = 11) %>%
  addLegend("topleft", 
              pal = pal_laborforce, 
              values = ~laborforce,
              opacity = 1,
              title="# Children")
  })
  
  output$slots_supply <- renderLeaflet({
    leaflet(neighborho_capacity_tract) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_slots(slots),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11) %>%
      addLegend("topleft", 
                pal = pal_slots, 
                values = ~slots,
                opacity = 1,
                title = "# Slots")
  })
  
  output$ratioslots_gap <- renderLeaflet({
    leaflet(EEC_census) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_ratioslots(ratioslots),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_ratioslots, 
                values = ~ratioslots,
                opacity = 1,
                title = "Ratio Slots")
  })
  
  output$ratioslots_bar <- renderPlot({
    ggplot(EEC_census_bar, aes(x = reorder(Name_neighborho,ratioslots), y = ratioslots)) +
      geom_bar(fill = "blue", 
               stat = "identity") + 
      ggtitle( "Childcare Ratio by Neighborhood") + 
      xlab("Neighborhoods") +  
      ylab("Children Under 6 to Available Early Ed Slots Ratio") +
      geom_hline(yintercept=1) +
      coord_flip()
  })
  ## HOURS
  output$percent_early <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_early(percent_early),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_early, 
                values = ~percent_early,
                opacity = 1,
                title = "% Early Workers")
  })
  
  output$percent_evening <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_evening(percent_evening),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_evening, 
                values = ~percent_evening,
                opacity = 1,
                title = "% Evening Workers")
  })
  
  output$percent_overnight <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_overnight(percent_overnight),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black", 
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addLegend("topleft", 
                pal = pal_overnight, 
                values = ~percent_overnight,
                opacity = 1,
                title = "% Overnight Workers")
  })
  
  output$aggregate_percent <- renderLeaflet({
    leaflet(hours_demand) %>%
      addProviderTiles("CartoDB")  %>%
      addPolygons(fillColor = ~pal_aggregate_percent(aggregate_percent),
                  weight = 2,
                  opacity = .8,
                  color = "white",
                  dashArray = "3",
                  fillOpacity = 0.7) %>%
      addPolygons(data = boston_neighborhood, 
                  weight = 2, 
                  opacity = 1, 
                  fillOpacity = 0, 
                  stroke = TRUE, 
                  color = "black",
                  label = ~Name) %>% #adding neighborhood data
      setView(lng = -71.057083, 
              lat = 42.361145, 
              zoom = 11.5) %>%
      addCircleMarkers(data = EEC_earlyed,
                       ~lon,
                       ~lat,
                       radius = 2.5,
                       opacity = 1,
                       color = ~infant_pal(Weekdays_off_hours),
                       label = ~as.character(Capacity),
                       group= "Show childcare providers with off hours weekday care") %>%
      addLayersControl(overlayGroups = c("Show childcare providers with off hours weekday care")) %>%
      addLegend("topleft", 
                pal = pal_aggregate_percent, 
                values = ~aggregate_percent,
                opacity = 1,
                title="Aggregated Percentage")
  })
}

## SHINYAPP

app <- shinyApp(ui, server)

runApp(app)

```


